spring:
  profiles: default

general:
  seed: 23417789
  paths:
    data: .data
    raw: .data/chunks
    supervised: .data/tables
    entities: .data/wiki/en
  resources:
    stopwords: stopwords.txt