spring:
  profiles: default


general:
  seed: 23417789
  paths:
    data: .data
    raw: .data/chunks
    supervised: .data/tables
    entities: .data/wiki/en
  resources:
    stopwords: stopwords.txt

---
spring:
  profiles: full
general:
  paths:
    entities: .data/wiki/en

---
spring:
  profiles: fast
general:
  paths:
    entities: .data/wiki/en/sample